import React from "react";
import Footer from "../../components/layout/Footer";

export default function TermsPage() {
  return (
    <div className="flex-1 flex flex-col bg-background select-none">
      <main className="flex-1 mx-auto max-w-3xl px-4 sm:px-6 lg:px-8 py-16 text-mutedText text-sm sm:text-md leading-relaxed font-sans">
        <h1 className="text-3xl sm:text-4xl font-extrabold font-display text-white mb-6">Terms of Service</h1>
        <p className="text-xs text-mutedText mb-8">Last updated: July 11, 2026</p>

        <section className="space-y-6">
          <div>
            <h2 className="text-lg font-bold font-display text-accent mb-2">1. Nature of Astrological Guidance</h2>
            <p>
              By using this service, you understand and agree that Vedic Astrology is entirely **interpretative**. Our AI Vedic Astrologer provides planetary insights, cycles, and traditional remedies based on celestial alignments. We do not make absolute predictions or guarantee specific outcomes in any dimension of life.
            </p>
          </div>

          <div>
            <h2 className="text-lg font-bold font-display text-accent mb-2">2. Professional Boundaries & Disclaimers</h2>
            <p>
              The guidance generated by the AI is for informational, spiritual, and educational purposes only. It is **not** a substitute for professional counsel.
            </p>
            <ul className="list-disc pl-5 mt-2 space-y-1 text-xs sm:text-sm">
              <li>**Medical Health**: Consult a licensed medical physician or therapist for health-related queries.</li>
              <li>**Financial Investments**: Consult a certified financial advisor before committing to investments.</li>
              <li>**Legal Issues**: Speak to an attorney or legal representative for lawsuits or contracts.</li>
            </ul>
          </div>

          <div>
            <h2 className="text-lg font-bold font-display text-accent mb-2">3. Acceptable Use</h2>
            <p>
              You agree not to exploit this application to execute malicious payloads, prompt injections, or script attacks. We reserve the right to block requests that violate security policies or exceed payload capacity.
            </p>
          </div>

          <div>
            <h2 className="text-lg font-bold font-display text-accent mb-2">4. Limitation of Liability</h2>
            <p>
              In no event shall the authors, operators, or contributors of AI Vedic Astrologer be held liable for any decisions, actions, or direct/indirect consequences arising from your usage of or reliance on our astrological interpretations.
            </p>
          </div>
        </section>
      </main>
      <Footer />
    </div>
  );
}
