from abc import ABC, abstractmethod
from typing import AsyncIterator, Dict, Any

class AIProvider(ABC):
    """
    Abstract Base Class for AI model providers.
    Decouples the core application from specific vendor SDKs.
    """
    @abstractmethod
    async def generate(self, prompt: str, system_instruction: str = None, config_override: Dict[str, Any] = None) -> str:
        """
        Generates a full synchronous response from the model.
        """
        pass

    @abstractmethod
    async def generate_stream(self, prompt: str, system_instruction: str = None, config_override: Dict[str, Any] = None) -> AsyncIterator[str]:
        """
        Yields tokens incrementally as they are generated by the model.
        """
        pass
